name: Bug Report
description: Report an issue with HiddenBot
title: "[ Bug ]: "
labels: ["bug"]
project: ["HiddenDevs/10"]
status: Planning
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Discord username
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue you are experiencing.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true